categories = Category.create([
  {categoryname:"Hotel",categorylao:"ໂຮງແຮມ"},
  {categoryname:"Food",categorylao:"ອາຫານ"},
  {categoryname:"Education",categorylao:"ການສຶກສາ"},
  {categoryname:"Wholesale",categorylao:"ຂາຍສົ່ງ"},
  {categoryname:"Retail",categorylao:"ຂາຍຍ່ອຍ"},
  {categoryname:"Service",categorylao:"ການບໍລິການ"},
  {categoryname:"Construction",categorylao:"ການກໍ່ສ້າງ"},
  {categoryname:"Clinic(Hospital)",categorylao:"ໂຮງໝໍ"},
  {categoryname:"Government Office",categorylao:"ຫ້ອງການລັດ"},
  {categoryname:"Bank",categorylao:"ທະນາຄານ"},
  {categoryname:"Manufactory",categorylao:"ໂຮງງານ"},
  {categoryname:"ransport",categorylao:"ການຂົນສົ່ງ"}
])

cities = City.create([
  {cityname: "Vientiane", city_lao: "ຄອນຫລວງວຽງຈັນ"},
  {cityname: "Luangparbang", city_lao: "ຫຼວງພະບາງ"},
  {cityname: "Champasak", city_lao:"ຈຳປາສັກ"}
])

districts = District.create([
{city_id: 1, districtname:"Parkngeun", district_lao:"ປາກງື່ມ"},
{city_id: 1, districtname:"Sisattanak", district_lao:"ສີສັດຕະນາກ"},
{city_id: 1, districtname:"Sikhottabong", district_lao:"ສີໂຄດຕະບອງ"},
{city_id: 1, districtname:"Chanthabury", district_lao:"ຈັນທະບູລີ"},
{city_id: 1, districtname:"saysettha", district_lao:"ໄຊເສດຖາ"},
{city_id: 1, districtname:"saythany", district_lao:"ໄຊທານີ"},
{city_id: 1, districtname:"Naxaythong", district_lao:"ນາຊາຍທອງ"},
{city_id: 1, districtname:"Hatsaifong", district_lao:"ຫາດຊາຍຟອງ"},
{city_id: 1, districtname:"Sangthong", district_lao:"ສັງທອງ"},

{city_id: 2, districtname:"Luangparbang", district_lao:"ຫຼວງພະບາງ"},
{city_id: 2, districtname:"Xiengngen", district_lao:"ຊຽງເງິນ"},
{city_id: 2, districtname:"Nan", district_lao:"ນານ"},
{city_id: 2, districtname:"Pakou", district_lao:"ປາກອູ"},
{city_id: 2, districtname:"Nambak", district_lao:"ນ້ຳບາກ"},
{city_id: 2, districtname:"Ngoy", district_lao:"ງອຍ"},
{city_id: 2, districtname:"Pakxeng", district_lao:"ປາກແຊງ"},
{city_id: 2, districtname:"Phonxai", district_lao:"ໂພນໄຊ"},
{city_id: 2, districtname:"Chomephet", district_lao:"ຈອມເພັດ"},
{city_id: 2, districtname:"Viengkham", district_lao:"ວຽງຄຳ"},
{city_id: 2, districtname:"Phoukhoun", district_lao:"ພູຄູນ"},
{city_id: 2, districtname:"Phongthon", district_lao:"ໂພນທອງ"},

{city_id: 3, districtname:"Paksa", district_lao:"ປາກເຊ"},
{city_id: 3, districtname:"Sanasomboun", district_lao:"ຊະນະສົມບູນ"},
{city_id: 3, districtname:"Bachiengchaleunsouk", district_lao:"ບາຈຽງຈະເລີນສຸກ"},
{city_id: 3, districtname:"Paksong", district_lao:"ປາກຊ່ອງ"},
{city_id: 3, districtname:"Pathoumphone", district_lao:"ປະທຸມພອນ"},
{city_id: 3, districtname:"Phonthong", district_lao:"ໂພນທອງ"},
{city_id: 3, districtname:"Champasak", district_lao:"ຈຳປາສັກ"},
{city_id: 3, districtname:"Soukhouma", district_lao:"ສຸກຄຸມາ"},
{city_id: 3, districtname:"Meanlapamok", district_lao:"ມິນລະປະໂມກ"},
{city_id: 3, districtname:"Khong", district_lao:"ໂຂງ"}

])

carbrands = Carbrand.create([
  {brandname: "BENZ", brand_option:1},
  {brandname: "BMW", brand_option:1},
  {brandname: "CHANA_CHANGAN", brand_option:1},
  {brandname: "CHERRY_CHERY", brand_option:1},
  {brandname: "GREAT WALL", brand_option:1},
  {brandname: "HONDA", brand_option:1},
  {brandname: "HYUNDAI", brand_option:1},
  {brandname: "KIA", brand_option:1},
  {brandname: "LIFAN", brand_option:1},
  {brandname: "MAZDA", brand_option:1},
  {brandname: "MG", brand_option:1},
  {brandname: "MITSUBISHI", brand_option:1},
  {brandname: "PROTON", brand_option:1},
  {brandname: "TOYOTA", brand_option:1},
  {brandname: "MOTOR CYCLE", brand_option:2},
  {brandname: "OTHER", brand_option:2}
])

carmodels = Carmodel.create([
  {brand_id: 1, modelname:"A Class (A45 ADC/T)"},
  {brand_id: 1, modelname:"A Class (A200 ASport DC/T)"},
  {brand_id: 1, modelname:"A Class (A250 Sport DC/T)"},
  {brand_id: 1, modelname:"B Class (B180 DC/T)"},
  {brand_id: 1, modelname:"B Class (B200 Sport (Night Package) DC/T)"},
  {brand_id: 1, modelname:"C Class (C200 Avantgarde A/T)"},
  {brand_id: 1, modelname:"C Class (C250 ASport A/T)"},
  {brand_id: 1, modelname:"CLA Class (CLA200 DC/T)"},
  {brand_id: 1, modelname:"CLA Class (CLA250 4Matic DC/T)"},
  {brand_id: 1, modelname:"CLA Class (Coupe)"},
  {brand_id: 1, modelname:"CLS Class (Coupe)"},
  {brand_id: 1, modelname:"E Class (E250 CDI Avantgarde A/T)"},
  {brand_id: 1, modelname:"E Class (E63 ADC/T)"},
  {brand_id: 1, modelname:"E Class (Cabriolet)"},
  {brand_id: 1, modelname:"E Class (Coupe)"},
  {brand_id: 1, modelname:"E Class (Sedan)"},
  {brand_id: 1, modelname:"E Class (Wagon)"},
  {brand_id: 1, modelname:"G Class (SUV)"},
  {brand_id: 1, modelname:"G Class (G500 A/T)"},
  {brand_id: 1, modelname:"G Class (G63 AA/T)"},
  {brand_id: 1, modelname:"GL Class (GL350 CDI ASport A/T)"},
  {brand_id: 1, modelname:"GL Class (SUV)"},
  {brand_id: 1, modelname:"GLE GLE250d (4MATIC A/T)"},
  {brand_id: 1, modelname:"GLE GLE350d (4MATIC A/T)"},
  {brand_id: 1, modelname:"GLE GLE450 (A4MATIC Coupe A/T)"},
  {brand_id: 1, modelname:"GLA Class (GLA45 ADC/T)"},
  {brand_id: 1, modelname:"GLA Class (GLA220 CDI ASport 4Matic DC/T)"},
  {brand_id: 1, modelname:"GLA Class (GLA250 Edition I 4Matic DC/T)"},
  {brand_id: 1, modelname:"GLA Class (SUV)"},
  {brand_id: 1, modelname:"GLC Class (GLC250 4MATIC A/T)"},
  {brand_id: 1, modelname:"GLK Class (SUV)"},
  {brand_id: 1, modelname:"M Class (SUV)"},
  {brand_id: 1, modelname:"Mercedes (AGT S)"},
  {brand_id: 1, modelname:"S Class (S500 A/T)"},
  {brand_id: 1, modelname:"S Class (Coupe)"},
  {brand_id: 1, modelname:"S Class (Sedan)"},
  {brand_id: 1, modelname:"SL Class (SL500 A/T)"},
  {brand_id: 1, modelname:"SL Class (SL350 A/T)"},
  {brand_id: 1, modelname:"SL Class (Roadster)"},
  {brand_id: 1, modelname:"SLK Class (SLK200 A/T)"},
  {brand_id: 1, modelname:"SLK Class (SLK250 A/T)"},
  {brand_id: 1, modelname:"SLK Class (SLK350 A/T)"},
  {brand_id: 1, modelname:"SLK Class (SLK55 AA/T)"},
  {brand_id: 1, modelname:"SLK Class (Roadster)"},
  {brand_id: 1, modelname:"AGT (GT S DC/T)"},
  
  {brand_id: 2, modelname:"X6(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"1 Series(M135i Hatch A/T)"},
  {brand_id: 2, modelname:"1 Series(116i Essential A/T)"},
  {brand_id: 2, modelname:"1 Series(118d Sport Essential A/T)"},
  {brand_id: 2, modelname:"1 Series(118d Urban Essential A/T)"},
  {brand_id: 2, modelname:"1 Series(116i Package A/T)"},
  {brand_id: 2, modelname:"1 Series(118d Urban Package A/T)"},
  {brand_id: 2, modelname:"1 Series(118d Sport Package A/T)"},
  {brand_id: 2, modelname:"X1(sDrive18 Essential A/T)"},
  {brand_id: 2, modelname:"X1(sDrive18d Package A/T)"},
  {brand_id: 2, modelname:"X1(sDrive18d xLine A/T)"},
  {brand_id: 2, modelname:"X1(sDrive18d Sport A/T)"},
  {brand_id: 2, modelname:"X1(sDrive18d M Sport A/T)"},
  {brand_id: 2, modelname:"2 Series Coupe (Coupe M235I A/T)"},
  {brand_id: 2, modelname:"2 Series Coupe (220i Coupe Sport Essential A/T)"},
  {brand_id: 2, modelname:"2 Series Coupe (220i Coupe Sport Package A/T)"},
  {brand_id: 2, modelname:"2 Series Active Tourer (218i Active Tourer Essential A/T)"},
  {brand_id: 2, modelname:"2 Series Active Tourer (218i Active Tourer Package A/T)"},
  {brand_id: 2, modelname:"3 Series(M3 Sedan Pure M/T)"},
  {brand_id: 2, modelname:"3 Series(M3 Sedan DC/T)"},
  {brand_id: 2, modelname:"3 Series(318d Essential A/T)"},
  {brand_id: 2, modelname:"3 Series(320d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"3 Series(318d Package A/T)"},
  {brand_id: 2, modelname:"3 Series(320d Luxury Package A/T)"},
  {brand_id: 2, modelname:"3 Series(320d Modern Package A/T)"},
  {brand_id: 2, modelname:"3 Series(320d Sport Package A/T)"},
  {brand_id: 2, modelname:"3 Series Gran Turismo (20d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"3 Series Gran Turismo (20d Sport Essential A/T)"},
  {brand_id: 2, modelname:"3 Series Gran Turismo (20d Modern Essential A/T)"},
  {brand_id: 2, modelname:"3 Series Gran Turismo (20d Sport Package A/T)"},
  {brand_id: 2, modelname:"3 Series Gran Turismo (20d Luxury Package A/T)"},
  {brand_id: 2, modelname:"3 Series Gran Turismo (20d Modern Package A/T)"},
  {brand_id: 2, modelname:"X3(sDrive18d SE Essential A/T)"},
  {brand_id: 2, modelname:"X3(xDrive20d xLine Essential A/T)"},
  {brand_id: 2, modelname:"X3(sDrive18d SE Package A/T)"},
  {brand_id: 2, modelname:"X3(XDrive20d xLine Package A/T)"},
  {brand_id: 2, modelname:"4 Series Coupe(M4 Coupe Pure M/T)"},
  {brand_id: 2, modelname:"4 Series Coupe(M4 Coupe DC/T)"},
  {brand_id: 2, modelname:"4 Series Coupe(420d Sport Essential A/T)"},
  {brand_id: 2, modelname:"4 Series Coupe(420d Sport Package A/T)"},
  {brand_id: 2, modelname:"4 Series Gran Coupe  (Sport Essential A/T)"},
  {brand_id: 2, modelname:"4 Series Gran Coupe  (Luxury Essential A/T)"},
  {brand_id: 2, modelname:"4 Series Gran Coupe  (Luxury Package A/T)"},
  {brand_id: 2, modelname:"4 Series Gran Coupe  (Sport Package A/T)"},
  {brand_id: 2, modelname:"X4(xDrive20d Essential A/T)"},
  {brand_id: 2, modelname:"X4(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"X4(xDrive20d Package A/T)"},
  {brand_id: 2, modelname:"X4(xDrive30d M Sport A/T)"},
  {brand_id: 2, modelname:"5 Series(520d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"5 Series(520d Modern Essential A/T)"},
  {brand_id: 2, modelname:"5 Series(530d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"5 Series(520d Modern Package A/T)"},
  {brand_id: 2, modelname:"5 Series(520d Luxury Package A/T)"},
  {brand_id: 2, modelname:"5 Series(530d Luxury Package A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(520d Modern Essential A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(520d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(520d Modern Package A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(520d Luxury Package A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(520d Luxury Package A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(530d Luxury A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(530d Modern Package A/T)"},
  {brand_id: 2, modelname:"5 Series Gran Turismo(530d Luxury Package A/T)"},
  {brand_id: 2, modelname:"X5(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"X5(xDrive30d Package A/T)"},
  {brand_id: 2, modelname:"X5(xDrive30d Experience A/T)"},
  {brand_id: 2, modelname:"X5(xDrive30d Excellence A/T)"},
  {brand_id: 2, modelname:"X5(xDrive30d M Sport A/T)"},
  {brand_id: 2, modelname:"6 Series(640i Gran Coupe Essential A/T)"},
  {brand_id: 2, modelname:"6 Series(640i Gran Coupe Package A/T)"},
  {brand_id: 2, modelname:"7 Series(730Li A/T)"},
  {brand_id: 2, modelname:"7 Series(740Li A/T)"},
  {brand_id: 2, modelname:"E24"},
  {brand_id: 2, modelname:"M3"},
  {brand_id: 2, modelname:"M5"},
  {brand_id: 2, modelname:"Z4(Drive20i Essential A/T)"},
  {brand_id: 2, modelname:"Z4(sDrive20i Package A/T)"},
  {brand_id: 2, modelname:"X6M"},

  {brand_id: 3, modelname:"Alsvin Sedan (1.5L)"},
  {brand_id: 3, modelname:"Alsvin Hatchback (1.5L)"},
  {brand_id: 3, modelname:"Alsvin V3 (1.3L)"},
  {brand_id: 3, modelname:"Alsvin V5 (1.5L)"},
  {brand_id: 3, modelname:"Alsvin V7 (1.5/1.6L)"},
  {brand_id: 3, modelname:"Benni (1.0/1.3L)"},
  {brand_id: 3, modelname:"Benni Mini (1.0L)"},
  {brand_id: 3, modelname:"Benni Love (1.3L)"},
  {brand_id: 3, modelname:"CS15 (1.5L)"},
  {brand_id: 3, modelname:"CS35 (1.6L)"},
  {brand_id: 3, modelname:"CS75 (1.8L)"},
  {brand_id: 3, modelname:"CX20 (1.4L)"},
  {brand_id: 3, modelname:"CX30 (1.6/2.0L)"},
  {brand_id: 3, modelname:"CX30 sedan (1.6/2.0L)"},
  {brand_id: 3, modelname:"E30 (pure-electric)"},
  {brand_id: 3, modelname:"Eado (1.6L)"},
  {brand_id: 3, modelname:"Eado EV (pure-electric)"},
  {brand_id: 3, modelname:"Eado XT (1.5/1.6L)"},
  {brand_id: 3, modelname:"Joice (Jiexun) (2.0L)"},
  {brand_id: 3, modelname:"JoiceHEV (1.5L)"},
  {brand_id: 3, modelname:"Raeton (1.8/2.0L)"},
  {brand_id: 3, modelname:"Z-Shine (Zhixiang) (1.6/2.0L)"},
  {brand_id: 3, modelname:"CM8 (1.3L)"},
  {brand_id: 3, modelname:"Eulove (1.2/1.4L)"},
  {brand_id: 3, modelname:"Eulove X6 (1.4L)"},
  {brand_id: 3, modelname:"Honor (1.3/1.5L)"},
  {brand_id: 3, modelname:"Oushang (1.1/1.5L)"},
  {brand_id: 3, modelname:"Ruixing (1.5L)"},
  {brand_id: 3, modelname:"Star (1.2L)"},
  {brand_id: 3, modelname:"Star 2 (1.0L)"},
  {brand_id: 3, modelname:"Star 3 (1.0/1.2L)"},
  {brand_id: 3, modelname:"Star 4500 (1.3L)"},
  {brand_id: 3, modelname:"Star 7 (1.4L)"},
  {brand_id: 3, modelname:"Star 9 (1.5L)"},
  {brand_id: 3, modelname:"Taurustar (1.3L)"},
  {brand_id: 3, modelname:"Zunxing (2.7L)"},

  {brand_id: 4, modelname:"S22L"},
  {brand_id: 4, modelname:"Q22L (Comfortable (11 seater) M/T)"},
  {brand_id: 4, modelname:"Q22B"},
  {brand_id: 4, modelname:"Q22"},
  {brand_id: 4, modelname:"X1"},
  {brand_id: 4, modelname:"Tiggo(2.0 CV/T)"},
  {brand_id: 4, modelname:"Tiggo FL"},
  {brand_id: 4, modelname:"Tiggo 5"},
  {brand_id: 4, modelname:"Arrizo7"},
  {brand_id: 4, modelname:"E5(1.8 CV/T)"},
  {brand_id: 4, modelname:"A3"},
  {brand_id: 4, modelname:"A3 HB"},
  {brand_id: 4, modelname:"E3"},
  {brand_id: 4, modelname:"Fulwin2 FL"},
  {brand_id: 4, modelname:"Fulwin2 FL HB"},
  {brand_id: 4, modelname:"Fulwin 2(1.5 M/T)"},
  {brand_id: 4, modelname:"Fulwin2 HB"},
  {brand_id: 4, modelname:"A1"},
  {brand_id: 4, modelname:"New QQ"},
  {brand_id: 4, modelname:"QQ3(1.0 Luxury M/T)"},

  {brand_id: 5, modelname:"Haval H3 (Hover / Changcheng Hafu)"},
  {brand_id: 5, modelname:"Haval H5"},
  {brand_id: 5, modelname:"Haval H6"},
  {brand_id: 5, modelname:"Haval H7"},
  {brand_id: 5, modelname:"Haval H8"},
  {brand_id: 5, modelname:"Haval H9"},
  {brand_id: 5, modelname:"Haval M2"},
  {brand_id: 5, modelname:"Haval M4"},
  {brand_id: 5, modelname:"Deer (Changcheng Dier)"},
  {brand_id: 5, modelname:"Steed 3"},
  {brand_id: 5, modelname:"Steed 5"},
  {brand_id: 5, modelname:"Wingle (Changcheng Fengjun)"},
  {brand_id: 5, modelname:"Wingle 5"},
  {brand_id: 5, modelname:"Coolbear (Changcheng Kuxiong)"},
  {brand_id: 5, modelname:"Florid (Changcheng Xuanli)"},
  {brand_id: 5, modelname:"Peri (Changcheng Jingling)"},
  {brand_id: 5, modelname:"Haval M1 (Peri 4x4)"},
  {brand_id: 5, modelname:"Voleex C10 (Ling Ao, Phenom, i7)"},
  {brand_id: 5, modelname:"Voleex C20R"},
  {brand_id: 5, modelname:"Voleex V80 (Cowry / Changcheng Jiayu)"},
  {brand_id: 5, modelname:"Voleex C30"},
  {brand_id: 5, modelname:"Voleex C50"},
  {brand_id: 5, modelname:"Voleex C70"},
  {brand_id: 5, modelname:"Safe (Changcheng Saifo/Saifu)"},
  {brand_id: 5, modelname:"Sailor"},
  {brand_id: 5, modelname:"Sing"},
  {brand_id: 5, modelname:"SoCool"},
  {brand_id: 5, modelname:"Pegasus"},
  {brand_id: 5, modelname:"Proteus"},

  {brand_id: 6, modelname:"City(1.5 E M/T"},
  {brand_id: 6, modelname:"City(1.5 E CV/T"},
  {brand_id: 6, modelname:"City(1.5 E NAVI+ M/T"},
  {brand_id: 6, modelname:"City(1.5 E NAVI+ CV/T"},
  {brand_id: 6, modelname:"City(1.5 VX NAVI+ CV/T"},
  {brand_id: 6, modelname:"City(1.5 VX Modulo CV/T"},
  {brand_id: 6, modelname:"City(1.5 VX+ NAVI+ CV/T"},
  {brand_id: 6, modelname:"ZEST (2006-present)"},
  {brand_id: 6, modelname:"Vamos (1970-1973, 1999-present)"},
  {brand_id: 6, modelname:"Stream (2000-present)"},
  {brand_id: 6, modelname:"StepWGN (1996-present)"},
  {brand_id: 6, modelname:"Shuttle (1994-present)"},
  {brand_id: 6, modelname:"Ridgeline (2006-present)"},
  {brand_id: 6, modelname:"Pilot (2003-present)(3.5 EXL A/T)"},
  {brand_id: 6, modelname:"Odyssey/Shuttle (international market) (1995-present)"},
  {brand_id: 6, modelname:"Odyssey (North American market) (1995-present)(2.4 EX-V Navi CV/T)"},
  {brand_id: 6, modelname:"NSX (1990-2005, 2015)"},
  {brand_id: 6, modelname:"N-One (2012-present)"},
  {brand_id: 6, modelname:"MDX (2003-present)"},
  {brand_id: 6, modelname:"Life (1971-1974, 1997-present)"},
  {brand_id: 6, modelname:"Legend (1985-present)(3.5 Sport Hybrid SH-AWD DC/T)"},
  {brand_id: 6, modelname:"Inspire (1990-present)"},
  {brand_id: 6, modelname:"Insight, a hybrid electric vehicle (2000-2006, 2009-present)"},
  {brand_id: 6, modelname:"Jazz(1.5 V M/T)"},
  {brand_id: 6, modelname:"Jazz(1.5 V CV/T)"},
  {brand_id: 6, modelname:"Jazz(1.5 VX CV/T)"},
  {brand_id: 6, modelname:"Jazz(1.5 VX+ CV/T)"},
  {brand_id: 6, modelname:"Fit"},
  {brand_id: 6, modelname:"FCX Clarity"},
  {brand_id: 6, modelname:"CR-V(2.0 V M/T)"},
  {brand_id: 6, modelname:"CR-V(2.0 V A/T)"},
  {brand_id: 6, modelname:"CR-V(2.0 V Cruiser Edition A/T)"},
  {brand_id: 6, modelname:"CR-V(.0 S A/T)"},
  {brand_id: 6, modelname:"CR-V(2.4 SX A/T)"},
  {brand_id: 6, modelname:"Civic(1.8 S M/T)"},
  {brand_id: 6, modelname:"Civic(1.8 S A/T)"},
  {brand_id: 6, modelname:"Civic(1.8 E A/T)"},
  {brand_id: 6, modelname:"Civic(1.8 E Modulo A/T)"},
  {brand_id: 6, modelname:"Civic(2.0 EL A/T)"},
  {brand_id: 6, modelname:"Civic(2.0 EL Mugen A/T)"},
  {brand_id: 6, modelname:"Hobio (2003-present)"},
  {brand_id: 6, modelname:"Freed (2008-present)"},
  {brand_id: 6, modelname:"Fit Aria (1981-present)"},
  {brand_id: 6, modelname:"Elysion (2004-present)"},
  {brand_id: 6, modelname:"Crosstour (2010-present)"},
  {brand_id: 6, modelname:"CR-Z, a hybrid electric vehicle (2011-Present)"},
  {brand_id: 6, modelname:"Civic Hybrid (2003-present)"},
  {brand_id: 6, modelname:"Caren (1990)"},
  {brand_id: 6, modelname:"Brio (2011-present)(1.3 S M/T)"},
  {brand_id: 6, modelname:"Brio (2011-present)(1.3 S A/T)"},
  {brand_id: 6, modelname:"Brio (2011-present)(1.3 V NAVI M/T)"},
  {brand_id: 6, modelname:"Brio (2011-present)(1.3 V NAVI A/T)"},
  {brand_id: 6, modelname:"Brio Amaze(1.3 E M/T)"},
  {brand_id: 6, modelname:"Brio Amaze(1.3 S A/T)"},
  {brand_id: 6, modelname:"Brio Amaze(1.3 V NAVI M/T)"},
  {brand_id: 6, modelname:"Brio Amaze(1.3 V NAVI A/T)"},
  {brand_id: 6, modelname:"Ballade (1982 – present)"},
  {brand_id: 6, modelname:"Airwave (2005-present)"},
  {brand_id: 6, modelname:"Acty (1977-present)"},
  {brand_id: 6, modelname:"Accord (1976-present)(2.4 S A/T)"},
  {brand_id: 6, modelname:"Accord (1976-present)(3.5 SV A/T)"},
  {brand_id: 6, modelname:"Wow"},
  {brand_id: 6, modelname:"Urban SUV"},
  {brand_id: 6, modelname:"SUT"},
  {brand_id: 6, modelname:"Step Bus"},
  {brand_id: 6, modelname:"SSM"},
  {brand_id: 6, modelname:"Small Hybrid Sports"},
  {brand_id: 6, modelname:"S360"},
  {brand_id: 6, modelname:"Remix"},
  {brand_id: 6, modelname:"Puyo"},
  {brand_id: 6, modelname:"OSM"},
  {brand_id: 6, modelname:"N800"},
  {brand_id: 6, modelname:"MV-99"},
  {brand_id: 6, modelname:"Model X"},
  {brand_id: 6, modelname:"Kiwami"},
  {brand_id: 6, modelname:"J-WJ"},
  {brand_id: 6, modelname:"J-VX"},
  {brand_id: 6, modelname:"J-MW"},
  {brand_id: 6, modelname:"J-MJ"},
  {brand_id: 6, modelname:"Imas"},
  {brand_id: 6, modelname:"HSC"},
  {brand_id: 6, modelname:"Gear"},
  {brand_id: 6, modelname:"Fuya-Jo"},
  {brand_id: 6, modelname:"FCX"},
  {brand_id: 6, modelname:"Dualnote (of DN-X) 　"},
  {brand_id: 6, modelname:"CR-Z(1.5 M/T)"},
  {brand_id: 6, modelname:"CR-Z(Modulo M/T)"},
  {brand_id: 6, modelname:"CR-Z(1.5 CV/T)"},
  {brand_id: 6, modelname:"CR-Z(Modulo CV/T)"},
  {brand_id: 6, modelname:"CR-Z(Mugen M/T)"},
  {brand_id: 6, modelname:"CR-Z(Mugen CV/T)"},
  {brand_id: 6, modelname:"ASM"},
  {brand_id: 6, modelname:"2008 RA108"},
  {brand_id: 6, modelname:"2007 RA107"},
  {brand_id: 6, modelname:"2006 RA106"},
  {brand_id: 6, modelname:"1969 R-1300"},
  {brand_id: 6, modelname:"1968 RA302"},
  {brand_id: 6, modelname:"1968 RA301"},
  {brand_id: 6, modelname:"1967 RA300"},
  {brand_id: 6, modelname:"1966 RA273"},
  {brand_id: 6, modelname:"1965 RA272"},
  {brand_id: 6, modelname:"1964 RA271"},
  {brand_id: 6, modelname:"1963–1967 T360"},
  {brand_id: 6, modelname:"TN360/TN-III"},
  {brand_id: 6, modelname:"TN-Acty"},
  {brand_id: 6, modelname:"Quint Integra"},
  {brand_id: 6, modelname:"2004–2009 FR-V, a 6 seater"},
  {brand_id: 6, modelname:"2004–2009 Edix"},
  {brand_id: 6, modelname:"2002–2011 Element"},
  {brand_id: 6, modelname:"2002–2008 Mobilio Spike"},
  {brand_id: 6, modelname:"2002–2007 That’s"},
  {brand_id: 6, modelname:"2001–2008 Mobilio  1.5 E M/T"},
  {brand_id: 6, modelname:"2001–2008 Mobilio  1.5 V CV/T"},
  {brand_id: 6, modelname:"2001–2008 Mobilio  1.5 RS w/ Nav CV/T"},
  {brand_id: 6, modelname:"2000–2004 Life Dunk"},
  {brand_id: 6, modelname:"1999–2009 S2000"},
  {brand_id: 6, modelname:"1999–2009 S2000"},
  {brand_id: 6, modelname:"1999–present HR-V  1.8 S CV/T"},
  {brand_id: 6, modelname:"1999–present HR-V  1.8 E CV/T"},
  {brand_id: 6, modelname:"1999–present HR-V  1.8 E Modulo CV/T"},
  {brand_id: 6, modelname:"1999–present HR-V  1.8 EL CV/T"},
  {brand_id: 6, modelname:"1999–present HR-V  1.8 EL Mugen CV/T"},
  {brand_id: 6, modelname:"1999–2004 LaGreat"},
  {brand_id: 6, modelname:"1999–2003 Avancier"},
  {brand_id: 6, modelname:"1998–2002 Capa"},
  {brand_id: 6, modelname:"1997–2002 Torneo"},
  {brand_id: 6, modelname:"1997–1999 EV Plus, an electric vehicle"},
  {brand_id: 6, modelname:"1996–2010 Partner Van"},
  {brand_id: 6, modelname:"1996–2002 S-MX"},
  {brand_id: 6, modelname:"1996–2002 Orthia"},
  {brand_id: 6, modelname:"1996–2001 Logo"},
  {brand_id: 6, modelname:"1995–2003 Sabe"},
  {brand_id: 6, modelname:"1994–2002 Passport"},
  {brand_id: 6, modelname:"1993–1998, 2008–2010 Crossroad"},
  {brand_id: 6, modelname:"1993–1997 Rafaga"},
  {brand_id: 6, modelname:"1992–2004 Domani"},
  {brand_id: 6, modelname:"1992–1997 CR-X del Sol"},
  {brand_id: 6, modelname:"1992–1995 NSX-R"},
  {brand_id: 6, modelname:"1991–1996 Beat"},
  {brand_id: 6, modelname:"1989–1997 Ascot"},
  {brand_id: 6, modelname:"1988–1994 Concerto"},
  {brand_id: 6, modelname:"1985–2007 Integra"},
  {brand_id: 6, modelname:"1985–1997 Today"},
  {brand_id: 6, modelname:"1983–1991 CR-X (a.k.a. Ballade Sports CR-X or Civic CR-X)"},
  {brand_id: 6, modelname:"1981–1999 Street"},
  {brand_id: 6, modelname:"1980–2002 Ballade"},
  {brand_id: 6, modelname:"1980–1985 Quintet"},
  {brand_id: 6, modelname:"1978–2001 Prelude"},
  {brand_id: 6, modelname:"1973–1974 Life Pick-Up"},
  {brand_id: 6, modelname:"1972–1974 Life StepVan"},
  {brand_id: 6, modelname:"1972 1300"},
  {brand_id: 6, modelname:"1970–1974, 1998–2002 Z"},
  {brand_id: 6, modelname:"1969–1972 N600"},
  {brand_id: 6, modelname:"1967–1970 N360/N400"},
  {brand_id: 6, modelname:"1966–1970 S800"},
  {brand_id: 6, modelname:"1966–1967 L800"},
  {brand_id: 6, modelname:"1965–1966 SM600"},
  {brand_id: 6, modelname:"1965 L700"},
  {brand_id: 6, modelname:"1964–1967 T500"},
  {brand_id: 6, modelname:"1964–1966 S600"},
  {brand_id: 6, modelname:"1963–1964 S500"},
  
  {brand_id: 7, modelname:"Tucson(2.0 GL M/T)"},
  {brand_id: 7, modelname:"Tucson(2.0 GL A/T)"},
  {brand_id: 7, modelname:"Tucson(2.0 GLS A/T)"},
  {brand_id: 7, modelname:"Tucson(2.0 R-eVGT GL 4WD A/T)"},
  {brand_id: 7, modelname:"New Tucson(2.0 E GL 2WD A/T)"},
  {brand_id: 7, modelname:"New Tucson(2.0 S GLS 2WD A/T)"},
  {brand_id: 7, modelname:"New Tucson(2.0 S GLS 2WD (dsl) A/T)"},
  {brand_id: 7, modelname:"New Tucson(2.0 L 4WD (dsl) A/T)"},
  {brand_id: 7, modelname:"Galloper"},
  {brand_id: 7, modelname:"Santa Fe(2001–present)(2.2 R-evgt 4×2 M/T)"},
  {brand_id: 7, modelname:"Santa Fe(2001–present)(2.2 R-evgt 4×2 A/T)"},
  {brand_id: 7, modelname:"Santa Fe(2001–present)(2.2 R-evgt 4×4 A/T)"},
  {brand_id: 7, modelname:"Grand Santa Fe(2.2 4WD A/T)"},
  {brand_id: 7, modelname:"Terracan"},
  {brand_id: 7, modelname:"Trajet"},
  {brand_id: 7, modelname:"Accent(1.4 E M/T)"},
  {brand_id: 7, modelname:"Accent(1.4 E CV/T)"},
  {brand_id: 7, modelname:"Accent(1.6 E (dsl) M/T)"},
  {brand_id: 7, modelname:"Accent(1.4 S GL M/T)"},
  {brand_id: 7, modelname:"Accent(1.6 E (dsl) A/T)"},
  {brand_id: 7, modelname:"Accent(Hatch 1.6 E (dsl) M/T)"},
  {brand_id: 7, modelname:"Accent(1.4 S CV/T)"},
  {brand_id: 7, modelname:"Accent(1.6 (dsl) DC/T)"},
  {brand_id: 7, modelname:"Accent(Hatch 1.6 E (dsl) A/T)"},
  {brand_id: 7, modelname:"Accent(1.4 L CV/T)"},
  {brand_id: 7, modelname:"Accent(Hatch 1.6 (dsl) DC/T)"},
  {brand_id: 7, modelname:"Atos (1997-2007)"},
  {brand_id: 7, modelname:"BlueOn"},
  {brand_id: 7, modelname:"Dynasty(1996)"},
  {brand_id: 7, modelname:"Elantra (1990–present)"},
  {brand_id: 7, modelname:"Eon(0.8 GL M/T)"},
  {brand_id: 7, modelname:"Eon(0.8 GLS M/T)"},
  {brand_id: 7, modelname:"Equus(1999–2016)"},
  {brand_id: 7, modelname:"Excel(1985–2000)"},
  {brand_id: 7, modelname:"Lavita (2007–2010)"},
  {brand_id: 7, modelname:"Genesis (2008–present)"},
  {brand_id: 7, modelname:"Genesis Coupe(2008–present)(2.0L FL Turbo A/T)"},
  {brand_id: 7, modelname:"Genesis Coupe(2008–present)(2.0L FL Turbo Brembo M/T)"},
  {brand_id: 7, modelname:"Genesis Coupe(2008–present)(2.0L FL Turbo A/T)"},
  {brand_id: 7, modelname:"Genesis Coupe(2008–present)(3.8L V6 Brembo M/T)"},
  {brand_id: 7, modelname:"Getz(2002–2011)"},
  {brand_id: 7, modelname:"Grandeur(1986–present)"},
  {brand_id: 7, modelname:"HB20(2012–present)"},
  {brand_id: 7, modelname:"Grand i10(2007–present)(1.0 E M/T)"},
  {brand_id: 7, modelname:"Grand i10(2007–present)(1.0 S M/T)"},
  {brand_id: 7, modelname:"Grand i10(2007–present)(1.0 E A/T)"},
  {brand_id: 7, modelname:"Grand i10(2007–present)(1.0 S A/T)"},
  {brand_id: 7, modelname:"Grand i10(2007–present)(1.0 L A/T)"},
  {brand_id: 7, modelname:"Grand i10(2007–present)(1.2 L A/T)"},
  {brand_id: 7, modelname:"i20"},
  {brand_id: 7, modelname:"i20 Cross Sport(1.4 GL M/T)"},
  {brand_id: 7, modelname:"i20 Cross Sport(1.4 GL A/T)"},
  {brand_id: 7, modelname:"i20 Cross Sport(1.4 GL (diesel) M/T)"},
  {brand_id: 7, modelname:"i20 WRC"},
  {brand_id: 7, modelname:"i30(2007–present)"},
  {brand_id: 7, modelname:"i40(2011–present)"},
  {brand_id: 7, modelname:"ix20(2010–present)"},
  {brand_id: 7, modelname:"Mistra(2013–present)"},
  {brand_id: 7, modelname:"Scoupe(1988–1995)"},
  {brand_id: 7, modelname:"Sonata(1985–present)(2.4 GLS A/T)"},
  {brand_id: 7, modelname:"Sonata(1985–present)(2.4 GLS Premium A/T)"},
  {brand_id: 7, modelname:"Stellar(1983–1997)"},
  {brand_id: 7, modelname:"Veloster(2011-present)"},
  {brand_id: 7, modelname:"Veracruz(2007–2015)"},
  {brand_id: 7, modelname:"Tiburon(1996–2009)"},
  {brand_id: 7, modelname:"Libero"},
  {brand_id: 7, modelname:"Porter(1977–present)"},
  {brand_id: 7, modelname:"Starex(1997–present)"},
  {brand_id: 7, modelname:"Grand Starex(CVX Luxury A/T)"},
  {brand_id: 7, modelname:"4.5 to 5-ton truck"},
  {brand_id: 7, modelname:"8 to 25-ton truck"},
  {brand_id: 7, modelname:"Blue-Will"},
  {brand_id: 7, modelname:"Nuvis"},
  {brand_id: 7, modelname:"Portico"},

 {brand_id: 8, modelname:"Sorento(2.2 EX AWD A/T)"},
 {brand_id: 8, modelname:"KM420"},
 {brand_id: 8, modelname:"Cadenza"},
 {brand_id: 8, modelname:"Rio(1.2L LX 4-DR M/T)"},
 {brand_id: 8, modelname:"Rio(1.2L SLX 4-DR M/T)"},
 {brand_id: 8, modelname:"Rio(1.4L EX 4-DR M/T)"},
 {brand_id: 8, modelname:"Rio(1.4L EX 4-DR A/T)"},
 {brand_id: 8, modelname:"Rio(1.4L EX 5-DR A/T)"},
 {brand_id: 8, modelname:"Picanto(1.0 LX M/T)"},
 {brand_id: 8, modelname:"Picanto(1.0 EX M/T)"},
 {brand_id: 8, modelname:"Picanto(1.2 EX M/T)"},
 {brand_id: 8, modelname:"Rondo"},
 {brand_id: 8, modelname:"Borrego"},
 {brand_id: 8, modelname:"Forte(Sedan 1.6 EX A/T)"},
 {brand_id: 8, modelname:"Forte(Koup 2.0 EX A/T)"},
 {brand_id: 8, modelname:"Forte(5 2.0 SX A/T)"},
 {brand_id: 8, modelname:"Cadenza/K7"},
 {brand_id: 8, modelname:"Venga"},
 {brand_id: 8, modelname:"Soul(1.6 LX CRDI M/T)"},
 {brand_id: 8, modelname:"Soul(1.6 LX CRDI A/T)"},
 {brand_id: 8, modelname:"Rio/Rio5/Pride"},
 {brand_id: 8, modelname:"Rino (expected March 2012)[dated info]"},
 {brand_id: 8, modelname:"Picanto/Morning"},
 {brand_id: 8, modelname:"Optima/Magentis/K5(2.4L EX A/T)"},
 {brand_id: 8, modelname:"K9/Quoris"},
 {brand_id: 8, modelname:"Forte/Cerato"},
 {brand_id: 8, modelname:"Forte Koup"},
 {brand_id: 8, modelname:"Cee’d/Cee’d SW/pro_cee’d"},
 {brand_id: 8, modelname:"Carnival/Sedona(2.2 LWB 11-seater A/T)"},
 {brand_id: 8, modelname:"Carnival/Sedona(2.2 EX LWB A/T)"},
 {brand_id: 8, modelname:"Carens/Rondo(1.7 LX 5-seater A/T)"},
 {brand_id: 8, modelname:"Carens/Rondo(1.7 LX A/T)"},
 {brand_id: 8, modelname:"Carens/Rondo(1.7 EX A/T)"},
 {brand_id: 8, modelname:"Sportage(2.0 EX 4×2 A/T)"},
 {brand_id: 8, modelname:"Sportage(2.0 LX 4×2 A/T)"},
 {brand_id: 8, modelname:"K2700/Strong/3000S/2500TCI- KMC only"},
 {brand_id: 8, modelname:"Granbird – KMC only"},
 {brand_id: 8, modelname:"K4000s – KMC only"},
 {brand_id: 8, modelname:"AM928 – KMC only"},
 {brand_id: 8, modelname:"Soul Hybrid"},
 {brand_id: 8, modelname:"Ray Plug-in hybrid"},
 {brand_id: 8, modelname:"cee’d Hybrid"},
 {brand_id: 8, modelname:"Spectra"},
 {brand_id: 8, modelname:"1974–1981 Brisa"},
 {brand_id: 8, modelname:"Opirus/Amanti"},
 {brand_id: 8, modelname:"Mohave/Borrego"},
 {brand_id: 8, modelname:"2000–2009 Spectra"},
 {brand_id: 8, modelname:"2000–2002 Combi (originally by Asia, since 1983)"},
 {brand_id: 8, modelname:"1995–2001 Credos/Clarus"},
 {brand_id: 8, modelname:"1992–2003 Sephia"},
 {brand_id: 8, modelname:"1987–1996 Concord/Capital"},
 {brand_id: 8, modelname:"1986–2000 Pride"},
 {brand_id: 8, modelname:"1975–1981 Brisa II/K303"},
 {brand_id: 8, modelname:"KCV III"},
 {brand_id: 8, modelname:"Vizen"},
 {brand_id: 8, modelname:"Streetrunner"},
 {brand_id: 8, modelname:"Slice"},
 {brand_id: 8, modelname:"Rondo Taxi"},
 {brand_id: 8, modelname:"Rondo SX"},
 {brand_id: 8, modelname:"Pop"},
 {brand_id: 8, modelname:"Multi S"},
 {brand_id: 8, modelname:"Kue"},
 {brand_id: 8, modelname:"KOUP"},
 {brand_id: 8, modelname:"KND-4"},
 {brand_id: 8, modelname:"Kee"},
 {brand_id: 8, modelname:"KCV-4 Mojave"},
 {brand_id: 8, modelname:"GT"},
 {brand_id: 8, modelname:"Club"},
 {brand_id: 8, modelname:"Alpha"},
 {brand_id: 8, modelname:"18+"},

 {brand_id: 9, modelname:"320(320 Ex)"},
 {brand_id: 9, modelname:"520(520 1.6 VIP)"},
 {brand_id: 9, modelname:"520(520 1.6 LX)"},
 {brand_id: 9, modelname:"520(520 1.3 LX)"},
 {brand_id: 9, modelname:"520(520 1.3 DX)"},
 {brand_id: 9, modelname:"620(620 1.6 LX)"},
 {brand_id: 9, modelname:"Foison(Foison 1.3)"},
 {brand_id: 9, modelname:"Mini Truck(Mini Truck 1.3)"},

 {brand_id: 10, modelname:"CX-7"},
 {brand_id: 10, modelname:"RX-8"},
 {brand_id: 10, modelname:"MX-5(SKYACTIV-G 2.0 M/T)"},
 {brand_id: 10, modelname:"MX-5(SKYACTIV-G 2.0 A/T)"},
 {brand_id: 10, modelname:"Atenza"},
 {brand_id: 10, modelname:"Axela"},
 {brand_id: 10, modelname:"Tribute"},
 {brand_id: 10, modelname:"BT-50(2.2L 4×2 M/T)"},
 {brand_id: 10, modelname:"BT-50(2.2L 4×2 A/T)"},
 {brand_id: 10, modelname:"BT-50(3.2L 4×4 A/T)"},
 {brand_id: 10, modelname:"2(SkyActiv S Sedan M/T)"},
 {brand_id: 10, modelname:"2(SkyActiv S Sedan A/T)"},
 {brand_id: 10, modelname:"2(SkyActiv V Hatch A/T)"},
 {brand_id: 10, modelname:"2(SkyActiv V Sedan A/T)"},
 {brand_id: 10, modelname:"2(SkyActiv R Sedan A/T)"},
 {brand_id: 10, modelname:"2(Speed A/T)"},
 {brand_id: 10, modelname:"3(1.5 Skyactiv V Sedan A/T)"},
 {brand_id: 10, modelname:"3(1.5 Skyactiv V Hatchback A/T)"},
 {brand_id: 10, modelname:"3(2.0 Skyactiv R Sedan A/T)"},
 {brand_id: 10, modelname:"3(2.0 Skyactiv R Hatchback A/T)"},
 {brand_id: 10, modelname:"3(2.0 Speed w/ BOSE A/T)"},
 {brand_id: 10, modelname:"6(2.5 A/T)"},
 {brand_id: 10, modelname:"6(2.5 Wagon A/T)"},
 {brand_id: 10, modelname:"CX-5(2.0 MAXX FWD A/T)"},
 {brand_id: 10, modelname:"CX-5(2.0 Pro FWD A/T)"},
 {brand_id: 10, modelname:"CX-5(2.5 Sport AWD A/T)"},
 {brand_id: 10, modelname:"CX-9(3.7L 4×4 AWD A/T)"},
 {brand_id: 10, modelname:"Takeri"},
 {brand_id: 10, modelname:"Taiki"},
 {brand_id: 10, modelname:"Shinari"},
 {brand_id: 10, modelname:"Senku"},
 {brand_id: 10, modelname:"Sassou"},
 {brand_id: 10, modelname:"Ryuga"},
 {brand_id: 10, modelname:"Nagare"},
 {brand_id: 10, modelname:"Minagi"},
 {brand_id: 10, modelname:"Kiyora"},
 {brand_id: 10, modelname:"Kazamai"},
 {brand_id: 10, modelname:"Kabura"},
 {brand_id: 10, modelname:"Kaan"},
 {brand_id: 10, modelname:"Hakaze"},
 {brand_id: 10, modelname:"Furai"},
 {brand_id: 10, modelname:"Activehicle (1999)"},
 {brand_id: 10, modelname:"MX-5 Superlight (2009)"},
 {brand_id: 10, modelname:"MX-04 (1987)"},
 {brand_id: 10, modelname:"MX-03 (1985)"},
 {brand_id: 10, modelname:"MX-02 (1983)"},
 {brand_id: 10, modelname:"MV-X (1997"},
 {brand_id: 10, modelname:"MS-X (1997)"},
 {brand_id: 10, modelname:"Miata Mono-Posto (1999)"},
 {brand_id: 10, modelname:"London Taxi (1993)"},
 {brand_id: 10, modelname:"Le Mans Prototype (1983)"},
 {brand_id: 10, modelname:"HR-X 2 (1993)"},
 {brand_id: 10, modelname:"HR-X (1991)"},
 {brand_id: 10, modelname:"Gissya (1991)"},
 {brand_id: 10, modelname:"CVS (1974)"},
 {brand_id: 10, modelname:"CU-X (1995)"},
 {brand_id: 10, modelname:"BU-X (1995)"},
 {brand_id: 10, modelname:"AZ550 (1989)"},
 {brand_id: 10, modelname:"MX-81 (1981)"},
 {brand_id: 10, modelname:"TD-R (1989)"},
 {brand_id: 10, modelname:"SW-X (1999)"},
 {brand_id: 10, modelname:"SU-V (1995)"},
 {brand_id: 10, modelname:"Secret Hideout (2001)"},
 {brand_id: 10, modelname:"RX-Evolv (1999)"},
 {brand_id: 10, modelname:"RX-500 (1970)"},
 {brand_id: 10, modelname:"RX-01 (1995)"},
 {brand_id: 10, modelname:"RX 87 (1967)"},
 {brand_id: 10, modelname:"Nextourer (1999)"},
 {brand_id: 10, modelname:"Neospace (1999)"},
 {brand_id: 10, modelname:"MX-Micro Sport (2004)"},
 {brand_id: 10, modelname:"MX-Flexa (2004)"},
 {brand_id: 10, modelname:"MX-Crossport (2005)"},
 {brand_id: 10, modelname:"MX Sportif (2003)"},
 {brand_id: 10, modelname:"MX Sport Tourier (2001)"},
 
 {brand_id: 11, modelname:"14/28"},
 {brand_id: 11, modelname:"14/40"},
 {brand_id: 11, modelname:"18/80"},
 {brand_id: 11, modelname:"M-type Midget"},
 {brand_id: 11, modelname:"C-type Midget"},
 {brand_id: 11, modelname:"D-type Midget"},
 {brand_id: 11, modelname:"F-type Magna"},
 {brand_id: 11, modelname:"J-type Midget"},
 {brand_id: 11, modelname:"K-type Magnette"},
 {brand_id: 11, modelname:"L-type Magna"},
 {brand_id: 11, modelname:"N-type Magnette"},
 {brand_id: 11, modelname:"P-type Midget"},
 {brand_id: 11, modelname:"TA Midget"},
 {brand_id: 11, modelname:"TB Midget"},
 {brand_id: 11, modelname:"TC Midget"},
 {brand_id: 11, modelname:"TD Midget"},
 {brand_id: 11, modelname:"TF Midget"},
 {brand_id: 11, modelname:"MGA"},
 {brand_id: 11, modelname:"Midget"},
 {brand_id: 11, modelname:"MGB"},
 {brand_id: 11, modelname:"MGC"},
 {brand_id: 11, modelname:"MGB GT V8"},
 {brand_id: 11, modelname:"RV8"},
 {brand_id: 11, modelname:"F"},
 {brand_id: 11, modelname:"TF"},
 {brand_id: 11, modelname:"Metro"},
 {brand_id: 11, modelname:"ZR"},
 {brand_id: 11, modelname:"3"},
 {brand_id: 11, modelname:"KN"},
 {brand_id: 11, modelname:"1100"},
 {brand_id: 11, modelname:"1300"},
 {brand_id: 11, modelname:"14/28"},
 {brand_id: 11, modelname:"14/40"},
 {brand_id: 11, modelname:"18/80"},
 {brand_id: 11, modelname:"VA"},
 {brand_id: 11, modelname:"Y-type"},
 {brand_id: 11, modelname:"Magnette ZA"},
 {brand_id: 11, modelname:"Magnette ZB"},
 {brand_id: 11, modelname:"Magnette Mk. III"},
 {brand_id: 11, modelname:"Magnette Mk. IV"},
 {brand_id: 11, modelname:"Maestro"},
 {brand_id: 11, modelname:"Montego"},
 {brand_id: 11, modelname:"ZS"},
 {brand_id: 11, modelname:"6"},
 {brand_id: 11, modelname:"5"},
 {brand_id: 11, modelname:"SA"},
 {brand_id: 11, modelname:"WA"},
 {brand_id: 11, modelname:"ZT"},
 {brand_id: 11, modelname:"7"},
 {brand_id: 11, modelname:"XPower SV"},
 {brand_id: 11, modelname:"18/100 Tigress"},
 {brand_id: 11, modelname:"Q-type"},
 {brand_id: 11, modelname:"R-type"},
 {brand_id: 11, modelname:"EX-E"},
 {brand_id: 11, modelname:"Metro van"},
 {brand_id: 11, modelname:"Express"},

{brand_id: 12, modelname:"Montero Sport(GLS 2WD A/T)"},
{brand_id: 12, modelname:"Montero Sport(GLS Premium 2WD A/T)"},
{brand_id: 12, modelname:"Montero Sport(GLS 4WD M/T)"},
{brand_id: 12, modelname:"Montero Sport(GT 4WD A/T)"},
{brand_id: 12, modelname:"Outlander (Formerly Airtrek)"},
{brand_id: 12, modelname:"Pajero(GLS 3.8G 4WD A/T)"},
{brand_id: 12, modelname:"Pajero(GLS 3.2D 4WD A/T)"},
{brand_id: 12, modelname:"Adventure also known as Freeca(2.5L TX M/T)"},
{brand_id: 12, modelname:"Adventure also known as Freeca(2.5L GX M/T)"},
{brand_id: 12, modelname:"Adventure also known as Freeca(2.5L GLX M/T)"},
{brand_id: 12, modelname:"Adventure also known as Freeca(2.5L GLS Sport M/T)"},
{brand_id: 12, modelname:"Adventure also known as Freeca(2.5L Super Sport M/T)"},
{brand_id: 12, modelname:"RVR"},
{brand_id: 12, modelname:"ASX Model(GLS 4×2 CV/T)"},
{brand_id: 12, modelname:"ASX Model(GSR 4×2 CV/T)"},
{brand_id: 12, modelname:"Aspire (8th Generation of Galant Model)"},
{brand_id: 12, modelname:"Carisma (1995–2004)"},
{brand_id: 12, modelname:"Debonair (1964–1998)"},
{brand_id: 12, modelname:"Diamante also known as Magna, Sigma, V3000, Verada (1990–2005)"},
{brand_id: 12, modelname:"Dignity (1999–2001)"},
{brand_id: 12, modelname:"Emeraude (7th Generation of Galant Model)"},
{brand_id: 12, modelname:"Eterna Sava (Pillarless Sedan Model)"},
{brand_id: 12, modelname:"Eterna Sigma (1983–1989)"},
{brand_id: 12, modelname:"Eterna (5th Generation of Galant Model)"},
{brand_id: 12, modelname:"Galant"},
{brand_id: 12, modelname:"Galant Sigma (1969–2012)"},
{brand_id: 12, modelname:"Galant Sports (1994–1996)"},
{brand_id: 12, modelname:"Lancer Cedia (2000–2007)"},
{brand_id: 12, modelname:"Lancer (1973–present)(EX GLX M/T)"},
{brand_id: 12, modelname:"Lancer (1973–present)(EX GLX A/T)"},
{brand_id: 12, modelname:"Lancer (1973–present)(EX MX A/T)"},
{brand_id: 12, modelname:"Lancer (1973–present)(EX GT-A 2.0 CV/T)"},
{brand_id: 12, modelname:"Mirage(1.2 GLX M/T)"},
{brand_id: 12, modelname:"Mirage(1.2 GLX CV/T)"},
{brand_id: 12, modelname:"Mirage(1.2 GLS M/T)"},
{brand_id: 12, modelname:"Mirage(1.2 GLS Special Edition M/T)"},
{brand_id: 12, modelname:"Mirage(1.2 GLS CV/T)"},
{brand_id: 12, modelname:"Mirage G4(G4 GX M/T)"},
{brand_id: 12, modelname:"Mirage G4(G4 GLX M/T)"},
{brand_id: 12, modelname:"Mirage G4(G4 GLX CV/T)"},
{brand_id: 12, modelname:"Mirage G4(G4 GLS M/T)"},
{brand_id: 12, modelname:"Mirage G4(G4 GLS CV/T)"},
{brand_id: 12, modelname:"Proudia"},
{brand_id: 12, modelname:"Sigma"},
{brand_id: 12, modelname:"Tredia"},
{brand_id: 12, modelname:"Strada(GL 4×2 M/T)"},
{brand_id: 12, modelname:"Strada(GLX 4×2 M/T)"},
{brand_id: 12, modelname:"Strada(GL 4×4 M/T)"},
{brand_id: 12, modelname:"Strada(GLX V 4×2 A/T)"},
{brand_id: 12, modelname:"Strada(GLS V 4×4 M/T)"},
{brand_id: 12, modelname:"Strada(GLS V 4×4 A/T)"},
{brand_id: 12, modelname:"Libero"},
{brand_id: 12, modelname:"Delica (1968–present)"},
{brand_id: 12, modelname:"Cordia (1982–1990)"},
{brand_id: 12, modelname:"Chariot (1983–2003)"},
{brand_id: 12, modelname:"Challenger (1996–2008)"},
{brand_id: 12, modelname:"Eclipse (1989–2011)"},
{brand_id: 12, modelname:"eK (2001–present)"},
{brand_id: 12, modelname:"FTO (1994–2000)"},
{brand_id: 12, modelname:"GTO (1990–2001)"},
{brand_id: 12, modelname:"i Miev (2009–present)"},
{brand_id: 12, modelname:"Legnum"},
{brand_id: 12, modelname:"L200(4X2 (Single Cab Chassis) M/T)"},
{brand_id: 12, modelname:"L200"},
{brand_id: 12, modelname:"L300(Deluxe CC w/ FB Body & Dual AC opt. M/T)"},
{brand_id: 12, modelname:"L300(Exceed CC w/ FB body & Dual AC opt. M/T)"},
{brand_id: 12, modelname:"L300(Exceed XV Dual AC M/T)"},

{brand_id: 13, modelname:"Saga"},
{brand_id: 13, modelname:"Persona"},
{brand_id: 13, modelname:"Preve"},
{brand_id: 13, modelname:"Inspira"},
{brand_id: 13, modelname:"Iriz"},
{brand_id: 13, modelname:"Satria Neo"},
{brand_id: 13, modelname:"Suprima S"},
{brand_id: 13, modelname:"Exora"},


{brand_id: 14, modelname:"FJ Cruiser Car Review(4×4 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.7 G 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 G 4×2 M/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 G 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 V 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 V (WP) 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(3.0 V 4×4 A/T)"},
{brand_id: 14, modelname:"Fortuner(3.0 V (WP) 4×4 A/T)"},
{brand_id: 14, modelname:"Highlander"},
{brand_id: 14, modelname:"Land Cruiser 200(4.5 A/T)"},
{brand_id: 14, modelname:"Land Cruiser 200(4.5 Premium A/T)"},
{brand_id: 14, modelname:"Prado(4.0 VX A/T)"},
{brand_id: 14, modelname:"Prado(3.0 VX Diesel M/T)"},
{brand_id: 14, modelname:"Prado(3.0 VX Diesel A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Active A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Active+ A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Premium A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Premium AWD A/T)"},
{brand_id: 14, modelname:"Sequoia"},
{brand_id: 14, modelname:"Venza"},
{brand_id: 14, modelname:"Tundra"},
{brand_id: 14, modelname:"Toyota Aygo Small Car"},
{brand_id: 14, modelname:"Allion"},
{brand_id: 14, modelname:"Aurion"},
{brand_id: 14, modelname:"Auris"},
{brand_id: 14, modelname:"Avalon"},
{brand_id: 14, modelname:"Belta"},
{brand_id: 14, modelname:"Camry(2.5 G A/T)"},
{brand_id: 14, modelname:"Camry(2.5 S A/T)"},
{brand_id: 14, modelname:"Camry(2.5 V A/T)"},
{brand_id: 14, modelname:"Camry(3.5 V6 A/T)"},
{brand_id: 14, modelname:"Century"},
{brand_id: 14, modelname:"Corolla Altis(1.6 E M/T)"},
{brand_id: 14, modelname:"Corolla Altis(1.6 G M/T)"},
{brand_id: 14, modelname:"Corolla Altis(1.6 G CV/T)"},
{brand_id: 14, modelname:"Corolla Altis(1.6 V CV/T)"},
{brand_id: 14, modelname:"Corolla Altis(2.0 V CV/T)"},
{brand_id: 14, modelname:"Crown"},
{brand_id: 14, modelname:"Etios"},
{brand_id: 14, modelname:"iQ"},
{brand_id: 14, modelname:"ist"},
{brand_id: 14, modelname:"Mark X"},
{brand_id: 14, modelname:"Matrix"},
{brand_id: 14, modelname:"Premio"},
{brand_id: 14, modelname:"Vios(1.3 Base M/T)"},
{brand_id: 14, modelname:"Vios(1.3 J M/T)"},
{brand_id: 14, modelname:"Vios(1.3 E M/T)"},
{brand_id: 14, modelname:"Vios(1.3 E A/T)"},
{brand_id: 14, modelname:"Vios(1.5 G M/T)"},
{brand_id: 14, modelname:"Vios(1.5 G (WP) M/T)"},
{brand_id: 14, modelname:"Vios(1.5 G A/T)"},
{brand_id: 14, modelname:"Vios(1.5 G (WP) A/T)"},
{brand_id: 14, modelname:"Wigo(1.0 E M/T)"},
{brand_id: 14, modelname:"Wigo(1.0 G M/T)"},
{brand_id: 14, modelname:"Wigo(1.0 G A/T)"},
{brand_id: 14, modelname:"Yaris(1.3 E M/T)"},
{brand_id: 14, modelname:"Yaris(1.3 E A/T)"},
{brand_id: 14, modelname:"Yaris(1.5 G A/T)"},
{brand_id: 14, modelname:"Vitz"},
{brand_id: 14, modelname:"Avensis"},
{brand_id: 14, modelname:"Avanza(1.3 J M/T)"},
{brand_id: 14, modelname:"Avanza(1.3 E M/T)"},
{brand_id: 14, modelname:"Avanza(1.3 E A/T)"},
{brand_id: 14, modelname:"Avanza(1.5 G M/T)"},
{brand_id: 14, modelname:"Avanza(1.5 G A/T)"},
{brand_id: 14, modelname:"bB"},
{brand_id: 14, modelname:"Condor"},
{brand_id: 14, modelname:"Comfort"},
{brand_id: 14, modelname:"Innova(2.0 J M/T)"},
{brand_id: 14, modelname:"Innova(2.5 J M/T)"},
{brand_id: 14, modelname:"Innova(2.0 E M/T)"},
{brand_id: 14, modelname:"Innova(2.5 E M/T)"},
{brand_id: 14, modelname:"Innova(2.0 E A/T)"},
{brand_id: 14, modelname:"Innova(2.0 G M/T)"},
{brand_id: 14, modelname:"Innova(2.5 E A/T)"},
{brand_id: 14, modelname:"Innova(2.5 G M/T"},
{brand_id: 14, modelname:"Innova(2.0 G A/T)"},
{brand_id: 14, modelname:"Innova(2.5 G A/T)"},
{brand_id: 14, modelname:"Innova(2.0 V A/T)"},
{brand_id: 14, modelname:"Innova(2.5 V A/T)"},
{brand_id: 14, modelname:"Ipsum"},
{brand_id: 14, modelname:"Isis"},
{brand_id: 14, modelname:"Noah"},
{brand_id: 14, modelname:"Porte"},
{brand_id: 14, modelname:"Ractis"},
{brand_id: 14, modelname:"Raum"},
{brand_id: 14, modelname:"Sienta"},
{brand_id: 14, modelname:"Verso"},
{brand_id: 14, modelname:"Alphard(3.5 A/T)"},
{brand_id: 14, modelname:"Coaster"},
{brand_id: 14, modelname:"Hiace(Commuter 2.5L M/T)"},
{brand_id: 14, modelname:"Hiace(GL Grandia 2.5L M/T)"},
{brand_id: 14, modelname:"Hiace(GL Grandia 2.5L A/T)"},
{brand_id: 14, modelname:"Hiace(Super Grandia (Fabric) A/T)"},
{brand_id: 14, modelname:"Hiace(Super Grandia (Leather) A/T)"},
{brand_id: 14, modelname:"Hiace(LXV A/T)"},
{brand_id: 14, modelname:"Hilux(2.4 J 4×2 M/T)"},
{brand_id: 14, modelname:"Hilux(2.4 E 4×2 M/T)"},
{brand_id: 14, modelname:"Hilux(2.4 G 4×2 M/T)"},
{brand_id: 14, modelname:"Hilux(2.4 G 4×2 A/T)"},
{brand_id: 14, modelname:"Hilux(2.8 G 4×4 M/T)"},
{brand_id: 14, modelname:"Hilux(2.8 G 4×4 A/T)"},
{brand_id: 14, modelname:"Previa(2.4 A/T)"},
{brand_id: 14, modelname:"Previa(2.4 (WP) A/T)"},
{brand_id: 14, modelname:"Previa(2.4 Q A/T)"},
{brand_id: 14, modelname:"Previa(2.4 Q (WP) A/T)"},
{brand_id: 14, modelname:"Sienna"},
{brand_id: 14, modelname:"Tacoma"},
{brand_id: 14, modelname:"Wish"},
{brand_id: 14, modelname:"Prius(1.8 Hybrid CV/T)"},
{brand_id: 14, modelname:"Prius(1.8 Hybrid (WP) CV/T)"},
{brand_id: 14, modelname:"Prius C(1.5 Standard CV/T)"},
{brand_id: 14, modelname:"Prius C(1.5 Full Option CV/T)"},
{brand_id: 14, modelname:"Sai"},
{brand_id: 14, modelname:"86(2.0 M/T)"},
{brand_id: 14, modelname:"86(2.0 (WP) M/T)"},
{brand_id: 14, modelname:"86(2.0 A/T)"},
{brand_id: 14, modelname:"86(2.0 (WP) A/T)"},
{brand_id: 14, modelname:"86(2.0 Aero M/T)"},
{brand_id: 14, modelname:"86(2.0 Aero (WP) M/T)"},
{brand_id: 14, modelname:"86(2.0 Aero A/T)"},
{brand_id: 14, modelname:"86(2.0 Aero (WP) A/T)"},
{brand_id: 14, modelname:"Sera (1990-1995)"},
{brand_id: 14, modelname:"Paseo (1991-1999)"},
{brand_id: 14, modelname:"Tercel (1978-1999)"},
{brand_id: 14, modelname:"Starlet (1973-1999)"},
{brand_id: 14, modelname:"Celica"},
{brand_id: 14, modelname:"Supra"},
{brand_id: 14, modelname:"Carina"},
{brand_id: 14, modelname:"MR2"}


])




users = User.create([
  {
    email: 'testor@gmail.com',
    name: 'bestbot',
    password: '5d93ceb70e2bf5daa84ec3d0cd2c731a',
    sex: 'f',
    tel: '01122223333',
    birthdate: '19991111',
    usertype: 'user'
  },
  {
    email: 'carpenta@hanmail.net',
    name: 'ilhwan',
    password: '5d93ceb70e2bf5daa84ec3d0cd2c731a',
    sex: 'm',
    tel: '01026092841',
    birthdate: '19991111',
    usertype: 'user'
  },
  {
    email: 'mc2e@nate.com',
    name: 'kyungkoo',
    password: '5d93ceb70e2bf5daa84ec3d0cd2c731a',
    sex: 'm',
    tel: '01033334444',
    birthdate: '19991111',
    usertype: 'company',
    marketname: 'sample market',
    marketphone: 'sample phone', 
    marketemail: 'market@sample.com',
    address: 'sample marekt address'
  }
])

markets = Market.create([
  {
    marketname: 'beuty shop',
    marketname_lao: 'beuty shop ບັນຊ',
    user_id: 1,
    category1: 'Accountants',
    category2: 'Transport Services',
    city: 'test city',
    district: 'test  district',
    address: 'test address',
    address_lao: 'test address lao',
    open1: '10:00',
    close1: '19:00',
    desc1: 'MON,TUE',
    open2: '9:00',
    close2: '15:00',
    desc2: 'THU, FRI',
    open3: '14:00',
    close3: '18:00',
    desc3: 'SAT, SUN',
    fax: '111-2222-2222',
    cellphone: '333-4444-4444',
    tel: '123-452-1134',
    email: '1@1.2',
    homepage: 'test.hompage.com',
    latitude: '21.2312321312',
    longitude: '32.42132132',
    delyn: 'no',
    detail_lao: 'detail lao test',
    detail_eng: 'detail eng test',
    keyword: 'testkeyword',
    keyword_lao: 'testkeyword_ບັນຊ'
  }
])




favorites = Favorite.create([
  {
    user_id: 1,
    data_id: 1,
    gubun:1
  }
])
